// <auto-generated />
using Jasmin.Db.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jasmin.Db.Migrations
{
    [DbContext(typeof(JasminDBContext))]
    partial class JasminDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jasmin.Db.Entities.ActualLoad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CourseProject")
                        .HasColumnType("bigint");

                    b.Property<long>("Coursework")
                        .HasColumnType("bigint");

                    b.Property<long>("Credit")
                        .HasColumnType("bigint");

                    b.Property<long>("Exam")
                        .HasColumnType("bigint");

                    b.Property<long>("Labwork")
                        .HasColumnType("bigint");

                    b.Property<long>("Lecture")
                        .HasColumnType("bigint");

                    b.Property<long>("Lesson")
                        .HasColumnType("bigint");

                    b.Property<long>("PlannedLoadId")
                        .HasColumnType("bigint");

                    b.Property<long>("Practice")
                        .HasColumnType("bigint");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<long>("Сonsultation")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ActualLoads");
                });

            modelBuilder.Entity("Jasmin.Db.Entities.Guide", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Bachelor")
                        .HasColumnType("bigint");

                    b.Property<long>("Department")
                        .HasColumnType("bigint");

                    b.Property<long>("MasterOne")
                        .HasColumnType("bigint");

                    b.Property<long>("MasterTwo")
                        .HasColumnType("bigint");

                    b.Property<long>("NIRS")
                        .HasColumnType("bigint");

                    b.Property<long>("Postgraduate")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<long>("YearId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("Jasmin.Db.Entities.GuideHour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DefenseHours")
                        .HasColumnType("bigint");

                    b.Property<long>("SemesterHours")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GuideHours");
                });

            modelBuilder.Entity("Jasmin.Db.Entities.PlannedLoad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CourseProject")
                        .HasColumnType("bigint");

                    b.Property<long>("Coursework")
                        .HasColumnType("bigint");

                    b.Property<long>("Credit")
                        .HasColumnType("bigint");

                    b.Property<long>("Exam")
                        .HasColumnType("bigint");

                    b.Property<long>("Labwork")
                        .HasColumnType("bigint");

                    b.Property<long>("Lecture")
                        .HasColumnType("bigint");

                    b.Property<long>("Lesson")
                        .HasColumnType("bigint");

                    b.Property<long>("Practice")
                        .HasColumnType("bigint");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("YearId")
                        .HasColumnType("bigint");

                    b.Property<long>("Сonsultation")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PlannedLoads");
                });

            modelBuilder.Entity("Jasmin.Db.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BeginYearId")
                        .HasColumnType("text");

                    b.Property<string>("EndYearId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Jasmin.Db.Entities.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<int>("Post")
                        .HasColumnType("integer");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Jasmin.Db.Entities.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Faculty")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Jasmin.Db.Entities.Year", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AcademicYear")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Years");
                });
#pragma warning restore 612, 618
        }
    }
}
